apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  chart:
    spec:
      chart: fluent-bit
      version: 2.8.11
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    service:
      logLevel: info
    metric:
      enabled: true
  interval: 1m
