apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metricbeat
  namespace: logging
spec:
  chart:
    spec:
      chart: metricbeat
      version: 7.17.3
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    metricbeatConfig:
      metricbeat.yml: |
        system:
          hostfs: /hostfs
        metricbeat.modules:
        - module: kubernetes
          metricsets:
            - container
            - node
            - pod
            - system
            - volume
          period: 10s
          hosts: ["localhost:10255"]
          processors:
          - add_kubernetes_metadata:
              in_cluster: true
        - module: kubernetes
          enabled: true
          metricsets:
            - event
        - module: system
          period: 10s
          metricsets:
            - cpu
            - load
            - memory
            - network
            - process
            - process_summary
          processes: ['.*']
          process.include_top_n:
            by_cpu: 5
            by_memory: 5
        - module: system
          period: 1m
          metricsets:
            - filesystem
            - fsstat
          processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
        output.elasticsearch:
          hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-es-master:9200}'
    
      kube-state-metrics-metricbeat.yml: |
        metricbeat.modules:
        - module: kubernetes
          enabled: true
          metricsets:
            - state_node
            - state_deployment
            - state_replicaset
            - state_pod
            - state_container
          period: 10s
          hosts: ["${KUBE_STATE_METRICS_HOSTS:kube-state-metrics:8080}"]
        output.elasticsearch:
          hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-es-master:9200}'
  interval: 1m
