apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metricbeat
  namespace: logging
spec:
  chart:
    spec:
      chart: metricbeat
      version: 7.17.3
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
