apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 39.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    defaultRules:
      create: false
    targerNamespace: monitoring
    service:
      port: 3000
      type: NodePort
      targetPort: 30184
  interval: 1m
