kind: Service
apiVersion: v1
metadata:
  name: grafana-ext
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    name: prometheus-operator-grafana
    port: 3000
    nodePort: 30185
  type: NodePort
