apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic
spec:
  chart:
    spec:
      chart: eck-operator
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    installCRDs: true
    targerNamespace: elastic
  interval: 1m

